import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://clvbsdxemchfoctokgrf.supabase.co',
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const products = [
  {
    title: 'Rose Quartz Ice Roller',
    slug: 'rose-quartz-ice-roller',
    description: 'Depuff and sculpt your face in 60 seconds. Real rose quartz stone stays cold longer than plastic. Reduces morning puffiness, tightens pores, and boosts glow instantly.',
    category: 'Skincare Tools',
    tiktok_category: 'Beauty & Personal Care',
    landed_cost: 6.00,
    shipping_cost: 2.50,
    selling_price: 24.99,
    margin_percent: 66.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=rose+quartz+ice+roller',
    hero_image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Viral on TikTok for depuffing routines. Best hook: show before/after puffiness. Film in morning light.',
  },
  {
    title: 'Electric Makeup Brush Cleaner',
    slug: 'electric-makeup-brush-cleaner',
    description: 'Clean 12 brush sizes in seconds — just spin and dip. No more dirty brushes ruining your makeup. Includes spinner handle + bowl. TikTok beauty hack must-have.',
    category: 'Makeup Tools',
    tiktok_category: 'Beauty & Personal Care',
    landed_cost: 8.00,
    shipping_cost: 3.00,
    selling_price: 29.99,
    margin_percent: 63.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=electric+makeup+brush+cleaner',
    hero_image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Insane demo product. The spin + color water reveal is the hook. Always goes viral in beauty niches.',
  },
  {
    title: 'Gua Sha Facial Tool + Jade Roller Set',
    slug: 'gua-sha-jade-roller-set',
    description: '2-piece facial lymphatic drainage set. Real jade stone, ergonomic grip. Lifts and sculpts in 5 minutes. Ancient technique, modern skincare ritual.',
    category: 'Skincare Tools',
    tiktok_category: 'Beauty & Personal Care',
    landed_cost: 7.00,
    shipping_cost: 2.50,
    selling_price: 22.99,
    margin_percent: 58.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=gua+sha+jade+roller+set',
    hero_image_url: 'https://images.unsplash.com/photo-1614004103929-83bd6b13e4c7?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Bundle increases perceived value. Show the before/after jawline sculpting. Target skincare-obsessed women 18-35.',
  },
  {
    title: 'Scalp Massager Shampoo Brush',
    slug: 'scalp-massager-shampoo-brush',
    description: 'Soft silicone bristles stimulate blood flow for hair growth while you shampoo. Works wet or dry. Removes buildup, reduces dandruff, feels incredible.',
    category: 'Hair Care',
    tiktok_category: 'Beauty & Personal Care',
    landed_cost: 4.00,
    shipping_cost: 2.00,
    selling_price: 16.99,
    margin_percent: 64.0,
    processing_time: 2,
    supplier_url: 'https://www.autods.com/products/?q=silicone+scalp+massager+shampoo+brush',
    hero_image_url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Low price = impulse buy. Huge in hair growth community. Hook: "I was losing my hair until I tried this."',
  },
  {
    title: 'Portable USB Mini Blender',
    slug: 'portable-usb-mini-blender',
    description: 'Make protein shakes, smoothies, and matcha lattes anywhere. USB-C rechargeable, 6 blades, 16oz. Fits in your bag. 20-second blend.',
    category: 'Kitchen Gadgets',
    tiktok_category: 'Kitchen & Dining',
    landed_cost: 12.00,
    shipping_cost: 4.00,
    selling_price: 39.99,
    margin_percent: 60.0,
    processing_time: 4,
    supplier_url: 'https://www.autods.com/products/?q=portable+usb+rechargeable+mini+blender',
    hero_image_url: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Demo gold. Show it blending frozen fruit in 20 seconds. Target gym/wellness crowd. "My morning routine" format.',
  },
  {
    title: 'Acupressure Mat & Pillow Set',
    slug: 'acupressure-mat-pillow-set',
    description: 'Over 6,000 acupressure points relieve back pain, neck tension, and stress in 20 minutes. Includes mat + neck pillow. Natural pain relief without pills.',
    category: 'Wellness',
    tiktok_category: 'Sports & Outdoors',
    landed_cost: 13.00,
    shipping_cost: 4.50,
    selling_price: 44.99,
    margin_percent: 61.0,
    processing_time: 4,
    supplier_url: 'https://www.autods.com/products/?q=acupressure+mat+pillow+set',
    hero_image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Huge wellness niche. Real reaction videos drive sales. Hook: lay on it, show the "ouch then ahhh" reaction.',
  },
  {
    title: 'LED Mushroom Night Light',
    slug: 'led-mushroom-night-light',
    description: '16 color-changing LED mushroom lamp. Touch control, 3 brightness levels, USB powered. The aesthetic room decor piece all over TikTok "room reveal" videos.',
    category: 'Home Decor',
    tiktok_category: 'Home & Living',
    landed_cost: 11.00,
    shipping_cost: 3.50,
    selling_price: 36.99,
    margin_percent: 60.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=led+mushroom+night+light+color+changing',
    hero_image_url: 'https://images.unsplash.com/photo-1604762511981-23d4f2d2ed28?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: '"Room check" and "aesthetic setup" videos drive this. Show it cycling colors in a dark room. Under 10 seconds = viral.',
  },
  {
    title: 'Posture Corrector Brace',
    slug: 'posture-corrector-brace',
    description: 'Adjustable figure-8 shoulder brace pulls shoulders back and straightens spine instantly. Wearable under clothes. Relieves back, neck, and shoulder pain from desk work.',
    category: 'Wellness',
    tiktok_category: 'Sports & Outdoors',
    landed_cost: 8.00,
    shipping_cost: 3.00,
    selling_price: 29.99,
    margin_percent: 63.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=posture+corrector+adjustable+back+brace',
    hero_image_url: 'https://images.unsplash.com/photo-1616279967983-ec413476e824?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Before/after posture transformation is the hook. "I wore this for 30 days" content format does incredibly well.',
  },
  {
    title: 'Portable Handheld Mist Fan',
    slug: 'portable-handheld-mist-fan',
    description: 'Water mist + fan combo keeps you cool anywhere. 3 speeds, 300ml tank, USB rechargeable, runs 8 hours. Perfect for summer, outdoor events, gym.',
    category: 'Summer Essentials',
    tiktok_category: 'Home & Living',
    landed_cost: 9.00,
    shipping_cost: 3.00,
    selling_price: 28.99,
    margin_percent: 59.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=portable+handheld+mist+fan+usb',
    hero_image_url: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Summer product — peak season now. Show it at a hot event or outdoor concert. "How I survived the heat" angle.',
  },
  {
    title: '3-in-1 Magnetic Wireless Charging Station',
    slug: '3-in-1-magnetic-wireless-charger',
    description: 'Charge phone, AirPods, and Apple Watch simultaneously. Foldable, travel-ready, MagSafe compatible. Clean desk solution everyone needs.',
    category: 'Tech Accessories',
    tiktok_category: 'Electronics',
    landed_cost: 14.00,
    shipping_cost: 3.50,
    selling_price: 44.99,
    margin_percent: 61.0,
    processing_time: 4,
    supplier_url: 'https://www.autods.com/products/?q=3+in+1+wireless+charging+station+magsafe',
    hero_image_url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: '"Desk setup" and "clean workspace" content does well. Show the cable-free desk transformation.',
  },
  {
    title: 'Fridge Organizer Bins Set (6-Piece)',
    slug: 'fridge-organizer-bins-set',
    description: 'Crystal-clear stackable bins with pull-out drawer design. Set of 6 different sizes. Transform your fridge from chaos to Pinterest-perfect in 10 minutes.',
    category: 'Kitchen & Organization',
    tiktok_category: 'Home & Living',
    landed_cost: 13.00,
    shipping_cost: 4.00,
    selling_price: 42.99,
    margin_percent: 60.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=clear+fridge+organizer+bins+set',
    hero_image_url: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Fridge organization reveals are a massive TikTok trend. Before/after format. "Satisfying fridge clean-out" angle.',
  },
  {
    title: 'Neck Cloud Cervical Traction Pillow',
    slug: 'neck-cloud-cervical-traction-pillow',
    description: 'Gentle stretch decompresses cervical spine and relieves neck pain in 10 minutes. Memory foam, ergonomic arc design. Used by chiropractors.',
    category: 'Wellness',
    tiktok_category: 'Health & Wellness',
    landed_cost: 10.00,
    shipping_cost: 3.50,
    selling_price: 34.99,
    margin_percent: 61.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=neck+cloud+cervical+traction+device',
    hero_image_url: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: '"I have neck pain from working at a desk" is relatable for millions. Real reaction video is the hook.',
  },
  {
    title: 'Silicone Reusable Food Storage Bags (Set of 4)',
    slug: 'silicone-reusable-food-bags',
    description: 'Leak-proof, airtight, oven/microwave/freezer/dishwasher safe. Replace 1,000+ plastic bags. Set of 4 sizes. The eco swap everyone is making.',
    category: 'Kitchen & Eco',
    tiktok_category: 'Kitchen & Dining',
    landed_cost: 9.00,
    shipping_cost: 3.00,
    selling_price: 28.99,
    margin_percent: 58.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=silicone+reusable+food+storage+bags+set',
    hero_image_url: 'https://images.unsplash.com/photo-1622557850710-46de3e0fcf22?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Eco content does well with conscious buyers. "Switching to zero plastic" series format. Show durability test.',
  },
  {
    title: 'Electric Facial Cleansing Brush',
    slug: 'electric-facial-cleansing-brush',
    description: 'Sonic vibration removes 10x more dirt and makeup than hands alone. Waterproof, 3 speeds, soft silicone bristles. Dermatologist recommended cleanse.',
    category: 'Skincare Tools',
    tiktok_category: 'Beauty & Personal Care',
    landed_cost: 11.00,
    shipping_cost: 3.00,
    selling_price: 36.99,
    margin_percent: 61.0,
    processing_time: 3,
    supplier_url: 'https://www.autods.com/products/?q=electric+silicone+facial+cleansing+brush+sonic',
    hero_image_url: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Show the dirty water reveal after using it for the first time. "I never knew my face was this dirty" hook converts extremely well.',
  },
  {
    title: 'Avocado Slicer 3-in-1 Kitchen Tool',
    slug: 'avocado-slicer-3-in-1',
    description: 'Split, pit, and slice a perfect avocado in 5 seconds. Ergonomic grip, BPA-free, dishwasher safe. The kitchen gadget in every "cooking hack" video.',
    category: 'Kitchen Gadgets',
    tiktok_category: 'Kitchen & Dining',
    landed_cost: 4.00,
    shipping_cost: 2.00,
    selling_price: 15.99,
    margin_percent: 62.0,
    processing_time: 2,
    supplier_url: 'https://www.autods.com/products/?q=avocado+slicer+pitter+3+in+1',
    hero_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    status: 'Researching',
    listing_status: 'Not Prepared',
    content_queue_status: 'Not Started',
    source_platform: 'manual',
    review_notes: 'Low price = easy impulse buy. Demo takes 5 seconds and looks satisfying. "Kitchen gadgets that actually work" format.',
  },
]

async function run() {
  console.log('Deleting all existing products...')
  const { error: deleteError } = await supabase
    .from('products')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000') // delete all

  if (deleteError) {
    console.error('Delete error:', deleteError.message)
    process.exit(1)
  }
  console.log('All products deleted.')

  console.log('Inserting new products...')
  for (const product of products) {
    const { error } = await supabase.from('products').insert({
      ...product,
      imported_at: new Date().toISOString(),
    })
    if (error) {
      console.error(`Failed to insert "${product.title}":`, error.message)
    } else {
      console.log(`✓ ${product.title}`)
    }
  }
  console.log('Done.')
}

run()
